# neucol toml
sources = []
headers = [
    "/Mods/kprocess_mod.f90",
    "/Mods/zeta_mod.f90",
    "/Mods/epinv2_mod.f90",
    "/Mods/mxdim_mod.f90",
    "/Mods/b0_mod.f90",
    "/Mods/ewinput_mod.f90",
    "/Mods/ckm1_mod.f90",
    "/Mods/zprods_decl_mod.f90",
    "/Mods/hdecaymode_mod.f90",
    "/Mods/plabel_mod.f90",
    "/Mods/yukawas_mod.f90",
    "/Mods/ewcouple_mod.f90",
    "/Mods/qqbggintnames_mod.f90",
    "/Mods/nodecay_mod.f90",
    "/Mods/mqq_mod.f90",
    "/Mods/blabels_mod.f90",
    "/Mods/nwz_mod.f90",
    "/Mods/limits_mod.f90",
    "/Mods/nplot_mod.f90",
    "/Mods/ggZZintegrals_mod.f90",
    "/Mods/zprods_com_mod.f90",
    "/Mods/first_mod.f90",
    "/Mods/msq_struc_mod.f90",
    "/Mods/removebr_mod.f90",
    "/Mods/mxpart_mod.f90",
    "/Mods/virt5ax_mod.f90",
    "/Mods/breit_mod.f90",
    "/Mods/toploops_mod.f90",
    "/Mods/noglue_mod.f90",
    "/Mods/zcouple_mod.f90",
    "/Mods/nf_mod.f90",
    "/Mods/ggZZ_mod.f90",
    "/Mods/scheme_mod.f90",
    "/Mods/facscale_mod.f90",
    "/Mods/heldefs_mod.f90",
    "/Mods/Cabibbo_mod.f90",
    "/Mods/sprods_decl_mod.f90",
    "/Mods/ZZdlabels_mod.f90",
    "/Mods/scalarselect_mod.f90",
    "/Mods/zcouple_cms_mod.f90",
    "/Mods/qcdcouple_mod.f90",
    "/Mods/process_mod.f90",
    "/Mods/zerowidth_mod.f90",
    "/Mods/masses_mod.f90",
    "/Mods/ppmax_mod.f90",
    "/Mods/lc_mod.f90",
    "/Mods/blha_mod.f90",
    "/Mods/mmsq_cs_mod.f90",
    "/Mods/interference_mod.f90",
    "/Mods/scale_mod.f90",
    "/Mods/constants_mod.f90",
    "/Mods/verbose_mod.f90",
    "/Mods/msq_cs_mod.f90",
    "/Mods/nproc_mod.f90",
    "/Mods/sprods_com_mod.f90",
    "/Mods/nlooprun_mod.f90",
    "/Mods/ZZclabels_mod.f90",
    "/Mods/ppwp2j_mod.f90",
    "/Mods/epinv_mod.f90",
    "/Mods/couple_mod.f90",
    "/Mods/nflav_mod.f90",
    "/Mods/docheck_mod.f90",
    "/Mods/part_mod.f90",
    "/Mods/maxd_mod.f90",
    "/Mods/pp_mod.f90",
    "/Mods/mpicommon_mod.f90",
    "/Mods/kpart_mod.f90",
    "/Mods/ckm_mod.f90",
    "/Mods/flags_mod.f90",
    "/Mods/ggZZcomputemp_mod.f90",
    "/Mods/ewcharge_mod.f90",
    "/Mods/nqcdjets_mod.f90",
]
