# neucol toml
headers = []

sources = [
    "/Need/dot.f",
    #"/Z/qqb_z.f",
    #"/Z/qqb_z_v.f",
    #"/Need/coupling.f",
    #"/Need/ckmfill.f",
    #"/Need/couplz_cms.f",
    #"/Need/cplx.f",
    #"/Need/dotem.f",
    #"/Need/dot.f",
    #"/Need/fixcms.f",
    #"/Need/i3m.f",
    #"/Need/lfunctions.f",
    #"/Need/lnrat.f",
    #"/Need/spinoru.f",
]
