# neucol toml
headers = []

sources = [
    # "/W/qqb_w.f",
    # "/W/qqb_w_g.f",
    # "/W/qqb_w_v.f",
    # "/W/ampqqbgll.f",
    # "/Need/dot.f",
    # "/Z/qqb_z.f",
    # "/Z/qqb_z_v.f",
    # "/Need/coupling.f",
    # "/Need/ckmfill.f",
    # "/Need/couplz_cms.f",
    # "/Need/cplx.f",
    # "/Need/dotem.f",
    # "/Need/dot.f",
    # "/Need/fixcms.f",
    # "/Need/i3m.f",
    # "/Need/lfunctions.f",
    # "/Need/lnrat.f",
    # "/Need/spinoru.f",
    # "/ggH/gg_h.f",
    "/ThreeJets/A5gfill.f",
    "/ThreeJets/A51mpmpp5g.f",
    "/ThreeJets/A5qbmqpgmgpgp.f",
    "/ThreeJets/fillamps_qbqggg.f",
    "/ThreeJets/A5qbmgmqpgpgp.f",
    "/ThreeJets/fillDij.f",
    "/ThreeJets/helfill.f",
    "/ThreeJets/A5NLOqbqggg.f",
    "/ThreeJets/A5qbmqpgpgmgp.f",
    "/ThreeJets/A5NLO4qg.f",
    "/ThreeJets/A5qbmgpqpgmgp.f",
    "/ThreeJets/fillRCij.f",
    "/ThreeJets/qqb_thrjet_v.f",
    "/ThreeJets/fillSij.f",
    "/ThreeJets/A5qbmgpqpgpgm.f",
    "/ThreeJets/A5NLOggggg.f",
    "/ThreeJets/A5qbmqpgpgpgm.f",
    "/ThreeJets/A51mmppp5g.f",
    "/ThreeJets/fillaij0.f",
    "/ThreeJets/fillEij.f",
]
