# neucol toml
sources = []
headers = [
    "/Mods/working/couple_mod.hpp",
    "/Mods/working/toploops_mod.hpp",
    "/Mods/working/sprods_com_mod.hpp",
    "/Mods/working/hdecaymode_mod.hpp",
    "/Mods/working/virt5ax_mod.hpp",
    "/Mods/working/process_mod.hpp",
    "/Mods/working/removebr_mod.hpp",
    "/Mods/working/zprods_decl_mod.hpp",
    "/Mods/working/plabel_mod.hpp",
    "/Mods/working/nwz_mod.hpp",
    "/Mods/working/nlooprun_mod.hpp",
    "/Mods/working/nplot_mod.hpp",
    "/Mods/working/scalarselect_mod.hpp",
    "/Mods/working/scheme_mod.hpp",
    "/Mods/working/epinv_mod.hpp",
    "/Mods/working/sprods_decl_mod.hpp",
    "/Mods/working/nproc_mod.hpp",
    "/Mods/working/zerowidth_mod.hpp",
    "/Mods/working/nflav_mod.hpp",
    "/Mods/working/flags_mod.hpp",
    "/Mods/working/mqq_mod.hpp",
    "/Mods/working/zprods_com_mod.hpp",
    "/Mods/working/nodecay_mod.hpp",
    "/Mods/working/noglue_mod.hpp",
    "/Mods/working/zcouple_cms_mod.hpp",
    "/Mods/working/msq_struc_mod.hpp",
    "/Mods/working/mmsq_cs_mod.hpp",
]
